/**
 * The migration runner — DESIGN.md §4: "Migrations are SQL files generated by
 * drizzle-kit and applied by a `migrate(driver)` function on app start."
 *
 * The SQL is embedded (see `./generated.ts`) rather than read from disk, so the
 * same code path runs on Expo, in the OPFS worker and in Node tests. Applied
 * migrations are recorded in `_migrations`; each one commits in its own
 * transaction, so a failure half-way leaves earlier migrations applied and the
 * failing one rolled back.
 */

import type { IsoTimestamp } from '@vigor/core';

import type { SqlDriver } from '../driver';
import { MIGRATIONS_TABLE } from '../schema';
import { MIGRATIONS } from './generated';
import type { AppliedMigration, Migration, MigrationResult } from './types';

const CREATE_MIGRATIONS_TABLE = `CREATE TABLE IF NOT EXISTS "${MIGRATIONS_TABLE}" (
  "tag" text PRIMARY KEY NOT NULL,
  "idx" integer NOT NULL,
  "hash" text NOT NULL,
  "appliedAt" text NOT NULL
)`;

const SELECT_APPLIED = `SELECT "tag", "idx", "hash", "appliedAt" FROM "${MIGRATIONS_TABLE}" ORDER BY "idx" ASC`;

const INSERT_APPLIED = `INSERT INTO "${MIGRATIONS_TABLE}" ("tag", "idx", "hash", "appliedAt") VALUES (?, ?, ?, ?)`;

/** Thrown when the database has been migrated by an incompatible build. */
export class MigrationIntegrityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MigrationIntegrityError';
  }
}

function rowToApplied(row: unknown[]): AppliedMigration {
  return {
    tag: String(row[0]),
    idx: Number(row[1]),
    hash: String(row[2]),
    appliedAt: String(row[3]) as IsoTimestamp,
  };
}

/** Reads `_migrations`, creating it first if this is a fresh database. */
export async function readAppliedMigrations(driver: SqlDriver): Promise<AppliedMigration[]> {
  await driver.run(CREATE_MIGRATIONS_TABLE, []);
  const { rows } = await driver.run(SELECT_APPLIED, []);
  return rows.map(rowToApplied);
}

/**
 * Brings `driver`'s database up to date.
 *
 * Safe to call on every app start: already-applied migrations are skipped, and
 * a migration whose file changed after it was applied raises rather than
 * silently diverging.
 */
export async function migrate(
  driver: SqlDriver,
  options: { now?: () => IsoTimestamp; migrations?: readonly Migration[] } = {},
): Promise<MigrationResult> {
  const now = options.now ?? (() => new Date().toISOString());
  const migrations = [...(options.migrations ?? MIGRATIONS)].sort((a, b) => a.idx - b.idx);

  const applied = await readAppliedMigrations(driver);
  const appliedByTag = new Map(applied.map((row) => [row.tag, row]));

  for (const row of applied) {
    const known = migrations.find((migration) => migration.tag === row.tag);
    if (!known) {
      throw new MigrationIntegrityError(
        `the database has migration "${row.tag}" applied, but this build does not ship it. ` +
          `Refusing to migrate a database written by a newer version of VigorEngine.`,
      );
    }
    if (known.hash !== row.hash) {
      throw new MigrationIntegrityError(
        `migration "${row.tag}" was applied with a different definition ` +
          `(recorded ${row.hash.slice(0, 12)}, shipped ${known.hash.slice(0, 12)}). ` +
          `Generated migrations are immutable — add a new one instead of editing it.`,
      );
    }
  }

  const result: MigrationResult = { applied: [], alreadyApplied: [] };

  for (const migration of migrations) {
    if (appliedByTag.has(migration.tag)) {
      result.alreadyApplied.push(migration.tag);
      continue;
    }
    await driver.transaction(async (tx) => {
      for (const statement of migration.statements) {
        await tx.run(statement, []);
      }
      await tx.run(INSERT_APPLIED, [migration.tag, migration.idx, migration.hash, now()]);
    });
    result.applied.push(migration.tag);
  }

  return result;
}
