import { vigorConfig } from '@vigor/eslint-config';

export default [
  ...vigorConfig({
    scope: 'app',
    react: true,
    globals: { __DEV__: 'readonly' },
    // Expo owns these; they are CommonJS and regenerated by the CLI.
    ignores: ['babel.config.js', 'metro.config.js', '.expo/**', 'expo-env.d.ts'],
  }),
  {
    // Jest loads its config and resolver through Node's CommonJS require,
    // before any transform runs — same situation as the `.cjs` block below.
    files: ['jest.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        module: 'writable',
        require: 'readonly',
        exports: 'writable',
        process: 'readonly',
      },
    },
  },
  {
    // The React Native resolver shim runs in Node's CommonJS loader, before
    // Vitest hands anything to Vite (see `vitest.config.mts`).
    files: ['test/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        module: 'writable',
        require: 'readonly',
        exports: 'writable',
        process: 'readonly',
      },
    },
  },
];
