import { vigorConfig } from '@vigor/eslint-config';

export default vigorConfig({
  scope: 'app',
  react: true,
  globals: { __DEV__: 'readonly' },
  // Expo owns these; they are CommonJS and regenerated by the CLI.
  ignores: ['babel.config.js', 'metro.config.js', '.expo/**', 'expo-env.d.ts'],
});
